package grafica;

import baseDatos.BaseTicket;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import baseDatos.ConectarmyBase;
import com.mycompany.tiempo_exm.Tiempo;
import java.awt.Color;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import sonido.Sonido;
import tienda_videojuegos.Juegos;
import tienda_videojuegos.Ticket;

/**
 *
 * @author andrea
 */
public class Tabla_Juego extends javax.swing.JFrame {

    Sonido musica = new Sonido();
    ConectarmyBase link = new ConectarmyBase();
    BaseTicket bt = new BaseTicket();
    DefaultTableModel model;
    Object codigoRecogido, nombreRecogido, precioRecogido;
    Tabla_Ticket tk = new Tabla_Ticket();
    Ticket t = new Ticket();
    static ListIterator it;
    /**
     * Creates new form Tabla_Juego
     */
    DefaultTableModel tabla = new DefaultTableModel();

    public Tabla_Juego() {
        initComponents();
        tabla.addColumn("codigo");
        tabla.addColumn("nombre");
        tabla.addColumn("consola");
        tabla.addColumn("precio");
        tabla.addColumn("unidades");
        jTable1.setModel(tabla);
        Tiempo t = new Tiempo();
        t.titulo();
        t.grados();
        t.tiempo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        refresh = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        show = new javax.swing.JButton();
        venta = new javax.swing.JButton();
        ticket = new javax.swing.JButton();
        music = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        codigo = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        consola = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        unidades = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 900));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "codigo", "nombre", "consola", "precio", "unidades"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jToolBar1.setRollover(true);

        refresh.setBackground(new java.awt.Color(204, 255, 255));
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Refresh_132187.png"))); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jToolBar1.add(refresh);

        modify.setBackground(new java.awt.Color(204, 255, 255));
        modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Save_as_132230.png"))); // NOI18N
        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        jToolBar1.add(modify);

        insert.setBackground(new java.awt.Color(204, 255, 255));
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Edit_132232.png"))); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jToolBar1.add(insert);

        delete.setBackground(new java.awt.Color(204, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Delete_132192.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jToolBar1.add(delete);

        search.setBackground(new java.awt.Color(204, 255, 255));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Search_132289.png"))); // NOI18N
        search.setText("Search");
        search.setMaximumSize(new java.awt.Dimension(119, 36));
        search.setPreferredSize(new java.awt.Dimension(119, 36));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jToolBar1.add(search);

        show.setBackground(new java.awt.Color(204, 255, 255));
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo.png"))); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jToolBar1.add(show);

        venta.setBackground(new java.awt.Color(204, 255, 255));
        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Euro_132272.png"))); // NOI18N
        venta.setText("Sell");
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });
        jToolBar1.add(venta);

        ticket.setBackground(new java.awt.Color(204, 255, 255));
        ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Price_list_132262.png"))); // NOI18N
        ticket.setText("Ticket");
        ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketActionPerformed(evt);
            }
        });
        jToolBar1.add(ticket);

        music.setBackground(new java.awt.Color(204, 255, 255));
        music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Music.png"))); // NOI18N
        music.setFocusable(false);
        music.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        music.setMaximumSize(new java.awt.Dimension(76, 36));
        music.setMinimumSize(new java.awt.Dimension(76, 36));
        music.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicActionPerformed(evt);
            }
        });
        jToolBar1.add(music);

        codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoMouseClicked(evt);
            }
        });

        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });

        consola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consolaMouseClicked(evt);
            }
        });

        precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioMouseClicked(evt);
            }
        });

        unidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidadesMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/codigo-qr.png"))); // NOI18N
        jLabel3.setText("Código");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/texto.png"))); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consola-de-juegos.png"))); // NOI18N
        jLabel2.setText("Consola");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_Coins_132337.png"))); // NOI18N
        jLabel4.setText("Precio");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo-num-simbolo-de-interfaz-rectangular-negro.png"))); // NOI18N
        jLabel5.setText("Unidades");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(consola)
                                .addComponent(precio)))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        if (consola.getText().isEmpty() || codigo.getText().isEmpty() || nombre.getText().isEmpty() || precio.getText().isEmpty() || unidades.getText().isEmpty()) {
            if (consola.getText().isEmpty()) {
                consola.setBackground(Color.RED);
            }
            if (codigo.getText().isEmpty()) {
                codigo.setBackground(Color.RED);
            }
            if (nombre.getText().isEmpty()) {
                nombre.setBackground(Color.RED);
            }
            if (precio.getText().isEmpty()) {
                precio.setBackground(Color.RED);
            }
            if (unidades.getText().isEmpty()) {
                unidades.setBackground(Color.RED);
            }
        } else {
            Juegos nuevo = new Juegos(codigo.getText(), nombre.getText(), consola.getText(), Float.parseFloat(precio.getText()), Integer.parseInt(unidades.getText()));
            link.insert(nuevo);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        link.modify(String.valueOf(codigoRecogido));

    }//GEN-LAST:event_modifyActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            i -= 1;
        }
        ArrayList juegos = link.mostrarJuegos();
        Iterator it = juegos.iterator();
        while (it.hasNext()) {
            Juegos usu = (Juegos) it.next();
            String[] col = new String[5];
            col[0] = usu.getCodigo();
            col[1] = usu.getNombre();
            col[2] = usu.getConsola();
            col[3] = String.valueOf(usu.getPrecio());
            col[4] = String.valueOf(usu.getUnidades());
            tabla.addRow(col);
            jTable1.setModel(tabla);
        }
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        link.delete(String.valueOf(codigoRecogido));
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        codigoRecogido = jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        precioRecogido = jTable1.getValueAt(jTable1.getSelectedRow(), 3);

//        int i = jTable1.getSelectedRow();
//
//        codigo.setText(model.getValueAt(i, 0).toString());
//        nombre.setText(model.getValueAt(i, 1).toString());
//        consola.setText(model.getValueAt(i, 2).toString());
//        precio.setText(model.getValueAt(i, 3).toString());
//        unidades.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketActionPerformed
        tk.setVisible(true);
        it = bt.mostrarTickets().listIterator();
        tk.jTextArea1.setText(String.valueOf(it.next()));
    }//GEN-LAST:event_ticketActionPerformed

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        int totalUni;
        int vent = Integer.parseInt(JOptionPane.showInputDialog("Unidades vendidas :????"));
        int unimenos = Integer.parseInt(String.valueOf(Tabla_Juego.jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
        if (unimenos < vent) {
            JOptionPane.showMessageDialog(null, "Imposible realizar venta.No hay suficientes unidades");
        } else {
            totalUni = unimenos - vent;

            bt.insertaTicket(new Ticket(bt.calcularNum(), Float.valueOf(String.valueOf(precioRecogido)), vent));

            link.venta(String.valueOf(codigoRecogido), totalUni);
        }
    }//GEN-LAST:event_ventaActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        int i = Integer.parseInt(JOptionPane.showInputDialog("** MENU **\n1)BUSCAR POR CODIGO\n2)BUSCAR POR NOMBRE"));
        String s;
        switch (i) {
            case 1:
                s = link.buscar(JOptionPane.showInputDialog("Introduce el codigo a buscar :"), 1).toString();
                jTextArea1.setText(s);
                break;
            case 2:
                s = link.buscar(JOptionPane.showInputDialog("Introduce el nombre a buscar :"), 2).toString();
                jTextArea1.setText(s);
                break;
        }
    }//GEN-LAST:event_searchActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if (codigoRecogido == null) {
            JOptionPane.showMessageDialog(null, "Seleccione un valor de la tabla");
        } else {
            String t = link.buscar(String.valueOf(codigoRecogido), 1).toString();
            jTextArea1.setText(t);
        }
    }//GEN-LAST:event_showActionPerformed

    private void codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoMouseClicked
        codigo.setBackground(Color.WHITE);
    }//GEN-LAST:event_codigoMouseClicked

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        nombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_nombreMouseClicked

    private void consolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consolaMouseClicked
        consola.setBackground(Color.WHITE);
    }//GEN-LAST:event_consolaMouseClicked

    private void precioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioMouseClicked
        precio.setBackground(Color.WHITE);
    }//GEN-LAST:event_precioMouseClicked

    private void unidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidadesMouseClicked
        unidades.setBackground(Color.WHITE);
    }//GEN-LAST:event_unidadesMouseClicked

    private void musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicActionPerformed
        musica.ReproducirSonido();
    }//GEN-LAST:event_musicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField consola;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton modify;
    private javax.swing.JButton music;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JButton refresh;
    private javax.swing.JButton search;
    private javax.swing.JButton show;
    private javax.swing.JButton ticket;
    private javax.swing.JTextField unidades;
    private javax.swing.JButton venta;
    // End of variables declaration//GEN-END:variables
}
